version: 2

jobs:
  build:
    docker:
      - image: ruby

    working_directory: ~/src
    
    steps:
      - checkout

      - deploy:
          name: Deploy to AWS S3
          command: |
            gem install dpl
            dpl \
              --provider=s3 \
              --region=ap-southeast-2 \
              --bucket=ebay-fee-calc \
              --cache_control="public, max-age=3600"
